### service constants
# count of columns
array_size: 37

# index of id constant
id_index:

# index of date constant
date_index: 1

### indexes of user column names
phoneNumber: 2
city: 3
causeRefused: 37
gender: 4
age: 5
lastMonthListen: 6
lastWeekListen: 7
whatRadioListenLastWeek: 8
yesterdayListen: 9
whereListen1: 10
timeInterval1: 11
whatRadioListen1: 12
whichDevice1: 13
whereListen2: 14
timeInterval2: 15
whatRadioListen2: 16
whichDevice2: 17
whereListen3: 18
timeInterval3: 19
whatRadioListen3: 20
whichDevice3: 21
whereListen4: 22
timeInterval4: 23
whatRadioListen4: 24
whichDevice4: 25
whereListen5: 26
timeInterval5: 27
whatRadioListen5: 28
whichDevice5: 29
whereListen6: 30
timeInterval6: 31
whatRadioListen6: 32
whichDevice6: 33
education: 34
profession: 35
operator: 36