### service constants
# count of columns
array_size: 90

# index of id constant
id_index:

# index of date constant
date_index: 1

### indexes of user column names
operator: 90
phoneNumber: 2
city: 3
gender: 4
age: 5
watchingTV: 6
watchingTVTime: 7
whatChannelsWatch: 8

howManyPeopleAtHome: 9
childrenUnder4years: 10
subscribe: 11

whatTVType1: 12
quantityOfChannels1: 13
tvProvider1: 14
containsBelarus51: 15
containsTNT1: 16
containsVTV1: 17
containsTV31: 18
containsMuzTV1: 19
containsDomashniy1: 20
containsEuropaPlus1: 21
containsPeretc1: 22
hasSmartTV1: 23
usesSmartTV1: 24

whatTVType2: 25
quantityOfChannels2: 26
tvProvider2: 27
containsBelarus52: 28
containsTNT2: 29
containsVTV2: 30
containsTV32: 31
containsMuzTV2: 32
containsDomashniy2: 33
containsEuropaPlus2: 34
containsPeretc2: 35
hasSmartTV2: 36
usesSmartTV2: 37

whatTVType3: 38
quantityOfChannels3: 39
tvProvider3: 40
containsBelarus53: 41
containsTNT3: 42
containsVTV3: 43
containsTV33: 44
containsMuzTV3: 45
containsDomashniy3: 46
containsEuropaPlus3: 47
containsPeretc3: 48
hasSmartTV3: 49
usesSmartTV3: 50

whatTVType4: 51
quantityOfChannels4: 52
tvProvider4: 53
containsBelarus54: 54
containsTNT4: 55
containsVTV4: 56
containsTV34: 57
containsMuzTV4: 58
containsDomashniy4: 59
containsEuropaPlus4: 60
containsPeretc4: 61
hasSmartTV4: 62
usesSmartTV4: 63

whatTVType5: 64
quantityOfChannels5: 65
tvProvider5: 66
containsBelarus55: 67
containsTNT5: 68
containsVTV5: 69
containsTV35: 70
containsMuzTV5: 71
containsDomashniy5: 72
containsEuropaPlus5: 73
containsPeretc5: 74
hasSmartTV5: 75
usesSmartTV5: 76

whatTVType6: 77
quantityOfChannels6: 78
tvProvider6: 79
containsBelarus56: 80
containsTNT6: 81
containsVTV6: 82
containsTV36: 83
containsMuzTV6: 84
containsDomashniy6: 85
containsEuropaPlus6: 86
containsPeretc6: 87
hasSmartTV6: 88
usesSmartTV6: 89